export enum MimeType {
	APPS_SCRIPT = 'application/vnd.google-apps.script',
	AUDIO = 'application/vnd.google-apps.audio',
	DRIVE_FILE = 'application/vnd.google-apps.file',
	DRIVE_FOLDER = 'application/vnd.google-apps.folder',
	FUSION_TABLE = 'application/vnd.google-apps.fusiontable',
	GOOGLE_DOC = 'application/vnd.google-apps.document',
	GOOGLE_DRAWING = 'application/vnd.google-apps.drawing',
	GOOGLE_FORM = 'application/vnd.google-apps.form',
	GOOGLE_SHEET = 'application/vnd.google-apps.spreadsheet',
	JAMBOARD = 'application/vnd.google-apps.jam',
	MY_MAPS = 'application/vnd.google-apps.map',
	PHOTO = 'application/vnd.google-apps.photo',
	SHORTCUT = 'application/vnd.google-apps.shortcut',
	SITE = 'application/vnd.google-apps.site',
	SLIDES = 'application/vnd.google-apps.presentation',
	THIRD_PARTY_SHORTCUT = 'application/vnd.google-apps.drive-sdk',
	UNKNOWN = 'application/vnd.google-apps.unknown',
	VIDEO = 'application/vnd.google-apps.video',
}
